### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [jlund/susanna-haswell-rowson_charlotte-temple#1]
chapter-8.xhtml:

- [X] The semicolons need to be outside of the `<em>` elements ([SEMOS 8.2.4](https://standardebooks.org/manual/1.6.4/8-typography#8.2.4)).

chapter-12.xhtml:

- [X] The verse at the beginning of the chapter is an epigraph. Both the chapter title and the verse goes inside a `<header>` element. The `<blockquote>` receives epigraph semantics. See [SEMOS 7.4.4](https://standardebooks.org/manual/1.6.4/7-high-level-structural-patterns#7.4.4) for examples.

chapter-20.xhtml:

- [X] The quote from Chapter of Accidents is also an epigraph ([SEMOS 7.4.4](https://standardebooks.org/manual/1.6.4/7-high-level-structural-patterns#7.4.4)).

- [X] The play dialog from Chapter of Accidents doesn't look like verse.

- [X] Chapter of Accidents should italicized and tagged as a play.

chapter-21.xhtml:

- [X] This chapter also starts with an epigraph ([SEMOS 7.4.4](https://standardebooks.org/manual/1.6.4/7-high-level-structural-patterns#7.4.4)).

chapter-22.xhtml:

- [X] In the letter, "TO" needs to be "To".

chapter-26.xhtml:

- [X] In the letter, "TO" needs to be "To".

chapter-27.xhtml:

- [X] This chapter also starts with an epigraph ([SEMOS 7.4.4](https://standardebooks.org/manual/1.6.4/7-high-level-structural-patterns#7.4.4)).

chapter-30.xhtml:

- [X] This chapter also starts with an epigraph ([SEMOS 7.4.4](https://standardebooks.org/manual/1.6.4/7-high-level-structural-patterns#7.4.4)).

endnotes.xhtml:

- [X] In Note 1, remove the trailing periods after the roman numerals ([SEMOS 8.8.5.3](https://standardebooks.org/manual/1.6.4/single-page#8.8.5.3)).

local.css:

- [X] The epigraphs require additional styling. Make sure to copy the CSS for all epigraphs ([SEMOS 7.4.1](https://standardebooks.org/manual/1.6.4/single-page#7.4.1)) and for epigraphs in section headers ([SEMOS 7.4.4.2](https://standardebooks.org/manual/1.6.4/single-page#7.4.4.2)).

**Comment by jlund** [comment]
Thanks, Emma! I just posted on the mailing list in more detail, but this is ready to review again.

**Comment by EmmaSweeney** [comment]
content.opf:
- [X]  The subject Drama is reserved for plays. A better subject for this book is Fiction.

endnotes.xhtml:

- [X] In Note 6, the "G." in "Colonel James G. Montrésor" needs to be tagged with `<abbr epub:type="z3998:given-name">`.
